name: argument-backend
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - cudatoolkit=11.7 
  - pandas
  - scikit-learn
  - joblib
  - tqdm
  - nltk
  - pip:
      - fastapi==0.95.2
      - uvicorn==0.22.0
      - torch==2.0.1
      - transformers==4.30.2
      - sentence-transformers==2.2.2
      - huggingface-hub==0.14.1
      - python-multipart
